# Generated by Django 5.2 on 2025-05-03 12:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("instructions", models.TextField()),
                ("portions", models.PositiveIntegerField(default=1)),
                (
                    "prep_time",
                    models.PositiveIntegerField(help_text="Prep time in minutes"),
                ),
                (
                    "cook_time",
                    models.PositiveIntegerField(help_text="Cook time in minutes"),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("last_cooked", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipes",
                        to="meals.category",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "quantity",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "units",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("g", "grams"),
                            ("kg", "kilograms"),
                            ("ml", "milliliters"),
                            ("l", "liters"),
                            ("tsp", "teaspoons"),
                            ("tbsp", "tablespoons"),
                            ("cup", "cups"),
                            ("item", "items"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=100)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="meals.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
