# Generated by Django 5.2 on 2025-05-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0002_auto_20250503_1356"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cook_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Cook time in minutes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="portions",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="prep_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Prep time in minutes", null=True
            ),
        ),
    ]
